source:
    client_id: "example_extractor"
    host: ${MQTT_HOST}

cognite:
    # Read these from environment variables
    host: ${COGNITE_BASE_URL}
    project: ${COGNITE_PROJECT}

    idp-authentication:
        token-url: ${COGNITE_TOKEN_URL}

        client-id: ${COGNITE_CLIENT_ID}
        secret: ${COGNITE_CLIENT_SECRET}
        scopes:
            - ${COGNITE_BASE_URL}/.default

logger:
    console:
        level: DEBUG

queues:
    event-size: 10000
    raw-size: 100000
    timeseries-size: 1000000
    upload-interval: 60
